spring:
  application:
    name: registry-service
server:
  port: ${SERVER_PORT:3999}

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    maxThreadsForPeerReplication: 0
    wait-time-in-ms-when-sync-empty: 0
